env:
  - name: "DATABRICKS_HOST"
    valueFrom: "DATABRICKS_HOST"
  - name: "DATABRICKS_TOKEN"
    valueFrom: "DATABRICKS_TOKEN"
  - name: "DATABRICKS_WAREHOUSE_ID"
    valueFrom: "DATABRICKS_WAREHOUSE_ID"

command: [
  "streamlit",
  "run",
  "main/app.py"
]

